name: 'Comment from File'
description: 'Add a PR comment from a file'
inputs:
  file_path:
    description: 'Path to the comment file'
    required: true
  github_token:
    description: 'GitHub token'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Read and post comment
      shell: bash
      run: |
        if [ -f "${{ inputs.file_path }}" ]; then
          BODY=$(cat "${{ inputs.file_path }}")
          BODY="${BODY//'%'/'%25'}"
          BODY="${BODY//$'\n'/'%0A'}"
          BODY="${BODY//$'\r'/'%0D'}"
          echo "BODY<<EOF" >> $GITHUB_ENV
          echo "$BODY" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
        else
          echo "BODY=Comment file not found: ${{ inputs.file_path }}" >> $GITHUB_ENV
        fi
    
    - name: Create comment
      uses: actions/github-script@v7
      with:
        github-token: ${{ inputs.github_token }}
        script: |
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: process.env.BODY
          })
