# Copyright 2020-2026 Intel Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0

# Owner(s): ["module: intel"]

"""Pytest wrapper around ``rn50.py``.

Runs the ResNet50 training profile as a subprocess (it is an argparse driven
script that calls ``sys.exit``) and turns the manual review of its artifacts
into pass/fail checks.
"""

import json
import os
import subprocess
import sys
from pathlib import Path

import torch
from torch.testing._internal.common_utils import run_tests, TestCase

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from profiling_test_utils import (  # noqa: E402
    kernel_events,
    kernel_summary,
    parse_profiler_table,
    parse_profiler_time,
    RUNTIME_OP_RE,
)

_HERE = Path(__file__).resolve().parent
RN50_SCRIPT = _HERE / "rn50.py"
PROFILE_PT = "profiling.fp32.train.pt"
TRACE_JSON = "rn50.log.json"
NUM_ITERATIONS = os.environ.get("RN50_NUM_ITERATIONS", "20")
XPU_DEVICE = os.environ.get("RN50_XPU_DEVICE", "0")
# Set to reuse the artifacts of a previous run instead of retraining.
REUSE_ARTIFACTS = os.environ.get("RN50_REUSE_ARTIFACTS", "0") == "1"

NAME_COLUMN = "Name"
CPU_TOTAL_COLUMN = "CPU total"
SELF_DEVICE_COLUMN = "Self XPU"
DEVICE_TOTAL_COLUMN = "XPU total"


class TestRn50Profiling(TestCase):
    @classmethod
    def setUpClass(cls):
        super().setUpClass()
        cls.workdir = Path.cwd()
        cls.pt_path = cls.workdir / PROFILE_PT
        cls.trace_path = cls.workdir / TRACE_JSON
        if REUSE_ARTIFACTS:
            return
        for artifact in (cls.pt_path, cls.trace_path):
            artifact.unlink(missing_ok=True)
        command = [
            sys.executable,
            "-u",
            str(RN50_SCRIPT),
            "-a",
            "resnet50",
            "--dummy",
            "./",
            "--num-iterations",
            NUM_ITERATIONS,
            "--xpu",
            XPU_DEVICE,
        ]
        print(f"\n===== [rn50] running {' '.join(command)} =====")
        subprocess.run(
            command,
            cwd=cls.workdir,
            env={**os.environ, "PROFILE": "1"},
            check=True,
        )

    def _table_rows(self):
        self.assertTrue(
            self.pt_path.is_file(),
            f"[rn50] {self.pt_path} was not generated by rn50.py",
        )
        table = torch.load(self.pt_path, weights_only=True)
        self.assertIsInstance(
            table, str, f"[rn50] {self.pt_path} does not hold a profiler table"
        )
        return table, parse_profiler_table(table)

    def _runtime_rows(self, rows):
        return [row for row in rows if RUNTIME_OP_RE.match(row[NAME_COLUMN])]

    def test_profile_pt_file_generated(self):
        table, rows = self._table_rows()
        print(f"\n===== [rn50] {PROFILE_PT} =====")
        print(table)
        self.assertTrue(rows, f"[rn50] {self.pt_path} holds an empty profiler table")

    def test_kernel_event_exists(self):
        self.assertTrue(
            self.trace_path.is_file(),
            f"[rn50] {self.trace_path} was not generated by rn50.py",
        )
        with open(self.trace_path) as f:
            events = json.load(f).get("traceEvents", [])
        kernels = kernel_events(events)

        print("\n===== [rn50] trace kernel summary =====")
        for name, (count, total) in sorted(
            kernel_summary(events).items(), key=lambda kv: -kv[1][1]
        ):
            print(f"  calls={count:<6d} total={total:12.3f}us  {name}")

        self.assertTrue(
            any(k.get("dur", 0) > 0 for k in kernels),
            f"[rn50] no XPU kernel with a positive duration in {TRACE_JSON} "
            f"({len(kernels)} kernel events found)",
        )

        _, rows = self._table_rows()
        with_device_time = [
            row[NAME_COLUMN]
            for row in rows
            if parse_profiler_time(row[DEVICE_TOTAL_COLUMN]) > 0
        ]
        self.assertTrue(
            with_device_time,
            f"[rn50] no row with a positive '{DEVICE_TOTAL_COLUMN}' in {PROFILE_PT}",
        )

    def test_runtime_ops_have_cpu_time_only(self):
        _, rows = self._table_rows()
        runtime_rows = self._runtime_rows(rows)

        print("\n===== [rn50] runtime ops (ur*) =====")
        for row in runtime_rows:
            print(
                f"  {row[NAME_COLUMN]:<58.58s} "
                f"cpu_total={row[CPU_TOTAL_COLUMN]:>12s} "
                f"xpu_total={row[DEVICE_TOTAL_COLUMN]:>12s}"
            )

        self.assertTrue(
            runtime_rows, f"[rn50] {PROFILE_PT} reports no runtime op (ur*)"
        )
        for row in runtime_rows:
            name = row[NAME_COLUMN]
            for column in (SELF_DEVICE_COLUMN, DEVICE_TOTAL_COLUMN):
                self.assertEqual(
                    parse_profiler_time(row[column]),
                    0,
                    f"[rn50] runtime op {name} must have no XPU time, "
                    f"'{column}' is {row[column]}",
                )
            self.assertGreater(
                parse_profiler_time(row[CPU_TOTAL_COLUMN]),
                0,
                f"[rn50] runtime op {name} must have CPU time, "
                f"'{CPU_TOTAL_COLUMN}' is {row[CPU_TOTAL_COLUMN]}",
            )


if __name__ == "__main__":
    run_tests()
