name: Linux Unit Test

inputs:
  ut_name:
    required: true
    type: string
    description: Which ut to launch

permissions: read-all

runs:
  using: composite
  steps:
    - name: op_ut
      shell: timeout 18000 bash -xe {0}
      run: |
        export PYTORCH_TEST_WITH_SLOW=1
        export PYTORCH_ENABLE_XPU_FALLBACK=1
        export UT_NAME=${{ inputs.ut_name }}
        mkdir -p ${{ github.workspace }}/ut_log/op_ut
        cd pytorch/third_party/torch-xpu-ops/test/xpu
        cp ${{ github.workspace }}/run.sh .
        ./run.sh
