name: inductor-xpu-e2e-test

inputs:
  suite:
    required: true
    type: string
    default: 'huggingface'
    description: Dynamo benchmarks test suite. huggingface,timm_models,torchbench. Delimiter is comma
  env_prepare:
    required: false
    description: If set to any value, will prepare suite test env
  dt:
    required: true
    type: string
    default: 'float32'
    description: Data precision of the test.float32,bfloat16,float16,amp_bf16,amp_fp16. Delimiter is comma
  mode:
    required: true
    type: string
    default: 'inference'
    description: inference,training. Delimiter is comma
  scenario:
    required: true
    type: string
    default: 'accuracy'
    description: accuracy,performance. Delimiter is comma
  cards:
    required: false
    type: string
    default: 'all'
    description: which cards can be used in the test
  pytorch:
    required: false
    type: string
    default: 'main'
    description: Pytorch branch/commit
  driver:
    required: false
    type: string
    default: 'lts'
    description: Driver lts/rolling

runs:
  using: composite
  steps:
    - name: Prepare ENV
      if: ${{ inputs.env_prepare }}
      shell: bash
      run: |
        if [[ ${{ inputs.suite }} == *"torchbench"* ]]; then
          python -c "import torch, torchvision, torchaudio"
          cd ./pytorch
          TORCHBENCH_COMMIT_ID=$(cat .github/ci_commit_pins/torchbench.txt)
          git clone https://github.com/pytorch/benchmark.git xpu-benchmark
          cd xpu-benchmark && git checkout $TORCHBENCH_COMMIT_ID
          # remove deps which will reinstall torch
          pip install --no-deps accelerate
          pip install --no-deps git+https://github.com/huggingface/pytorch-image-models@v1.0.14
          pip install $(curl -sSL https://raw.githubusercontent.com/huggingface/pytorch-image-models/v1.0.14/requirements.txt | grep -vE torch)
          pip install -U transformers==4.44.2
          sed -i 's+.*pytorch-image-models.*++g;s+^accelerate.*++g;s/^transformers.*//g'  requirements.txt
          git status && git diff
          pip install -r requirements.txt
          python install.py --continue_on_fail
          # deps for torchrec_dlrm
          pip install pyre_extensions
          pip install fbgemm-gpu --index-url https://download.pytorch.org/whl/cpu
          pip install --no-deps lightning-utilities==0.14.3 torchmetrics==1.0.3 tensordict torchrec
        fi
        if [[ ${{ inputs.suite }} == *"huggingface"* ]]; then
          pip install -U transformers==4.44.2
        fi
        if [[ ${{ inputs.suite }} == *"timm_models"* ]]; then
          # install timm without dependencies
          pip install --no-deps git+https://github.com/huggingface/pytorch-image-models@v1.0.14
          # install timm dependencies without torch and torchvision
          pip install $(curl -sSL https://raw.githubusercontent.com/huggingface/pytorch-image-models/v1.0.14/requirements.txt | grep -vE torch)
        fi
        pip list |grep -E 'intel|torch'
    - name: E2E Test (${{ inputs.suite }} ${{ inputs.dt }} ${{ inputs.mode }} ${{ inputs.scenario }})
      shell: bash
      run: |
        cp ./.github/scripts/inductor_xpu_test.sh ./pytorch
        cd ./pytorch
        # check param
        function contains() {
            contains_status="echo 'Start $2 ...'"
            {
              [[ $1 =~ (^|,)$2($|,) ]]
            } || {
              echo "[Warning] $2 is not suppotted type! Skipped!"
              contains_status="continue"
            }
        }
        set -xe
        xpu_num=$(clinfo --list |awk 'BEGIN{gpu=0;}{if(gpu==1 && $0~/Platform/){gpu=0;}; if(gpu==1){print $0;}; if($0~/Platform.*Graphics/){gpu=1;}}' |wc -l)
        cores_per_instance="$(lscpu |grep -E 'Core\(s\) per socket:|Socket\(s\):' |awk -v i="${xpu_num}" 'BEGIN{sum=1}{sum*=$NF}END{print sum/i}')"
        export OMP_NUM_THREADS=${cores_per_instance}
        for suite in $(echo ${{ inputs.suite }} |sed 's/,/ /g')
        do
          if [ "${suite}" == "pt2e" ];then
            continue
          fi
          contains "huggingface,timm_models,torchbench" $suite
          $contains_status
          for dt in $(echo ${{ inputs.dt }} |sed 's/,/ /g')
          do
            contains "float32,bfloat16,float16,amp_bf16,amp_fp16" $dt
            $contains_status
            for mode in $(echo ${{ inputs.mode }} |sed 's/,/ /g')
            do
              contains "inference,training" $mode
              $contains_status
              for scenario in $(echo ${{ inputs.scenario }} |sed 's/,/ /g')
              do
                contains "accuracy,performance" $scenario
                $contains_status
                if [ "${MODEL_ONLY_NAME}" == "" ];then
                  for xpu_id in $(seq 0 $[ ${xpu_num} - 1 ])
                  do
                    cpu_list="$(echo "${cores_per_instance} ${xpu_id}" |awk '{printf("%d-%d", $1*$2, $1*$2+$1-1)}')"
                    numactl --localalloc --physcpubind=${cpu_list} bash inductor_xpu_test.sh ${suite} ${dt} ${mode} ${scenario} xpu ${xpu_id} static ${xpu_num} ${xpu_id} &
                  done
                else
                  for test_model in $(echo ${MODEL_ONLY_NAME} |sed 's/,/ /g')
                  do
                    numactl --localalloc bash inductor_xpu_test.sh ${suite} ${dt} ${mode} ${scenario} xpu 0 static 1 0 ${test_model}
                  done
                fi
                wait
                # summarize pass rate
                LOG_DIR="inductor_log/${suite}/${dt}"
                LOG_NAME=inductor_${suite}_${dt}_${mode}_xpu_${scenario}_all.log
                rm -f ${LOG_DIR}/${LOG_NAME}
                find ${LOG_DIR}/ -name "inductor_${suite}_${dt}_${mode}_xpu_${scenario}_card*.log" |xargs cat >> ${LOG_DIR}/${LOG_NAME} 2>&1
              done
            done
          done
        done

    - name: Summary E2E Test (${{ inputs.suite }} ${{ inputs.dt }} ${{ inputs.mode }} ${{ inputs.scenario }})
      env:
        HUGGING_FACE_HUB_TOKEN: ${{ inputs.hf_token }}
      shell: bash
      run: |
        cd ./pytorch
        rm -f inductor_log/summary_accuracy.csv
        for var in $(find inductor_log/ -name "inductor_*_xpu_accuracy.csv")
        do
          sed -i "s/$/,$(basename $var)/" $var
          cat $var >> inductor_log/summary_accuracy.csv
        done
        cd ${{ github.workspace }}
        cp ./.github/scripts/inductor_summary.py ./pytorch
        cd ./pytorch
        pip install styleFrame scipy pandas
        set -xe
        dt=$(echo ${{ inputs.dt }} |sed 's/,/ /g')
        mode=$(echo ${{ inputs.mode }} |sed 's/,/ /g')
        suite=$(echo ${{ inputs.suite }} |sed 's/,/ /g')
        scenario=$(echo ${{ inputs.scenario }} |sed 's/,/ /g')
        python inductor_summary.py -p ${dt} -s ${suite} -m ${mode} -sc ${scenario}
