name: Transformers Tests

inputs:
  test_case:
    type: string
    default: ''
    description: Test to run, 'tests_backbone, tests_py, tests_generation, tests_models_<shard num>_<shard id>, tests_trainer or tests_utils'

runs:
  using: composite
  steps:
    - name: Test Comments
      shell: bash -x -e {0}
      run: |
        # Excluding tests due to:
        # * torch.distributed.* not yet supported by XPU
        # *'tests/utils/test_import_utils.py' invalidates state of the test engine causing
        #   next tests to fail. See: https://github.com/huggingface/transformers/issues/36267
        # * https://github.com/huggingface/transformers/issues/36267 (marian tests)
        # * https://github.com/pytorch/pytorch/issues/140965 (aten::_linalg_eigvals)
        echo "Start test: ${{ inputs.test_name }}"
        if [ $(echo ${{ inputs.test_name }} |grep -c "_[0-9]*$") -ne 0 ];then
          shard_options="$(echo ${{ inputs.test_name }} |awk -F '_' '{printf("--num-shards %s --shard-id %s", $(NF-1), $NF)}')"
        else
          shard_options=""
        fi
        PYTEST_ADDOPTS+=" ${shard_options} --make-reports=${{ inputs.test_name }} --junit-xml=reports/${{ inputs.test_name }}.xml "
        echo "PYTEST_ADDOPTS=\"${PYTEST_ADDOPTS}\"" >> ${GITHUB_ENV}
    - name: Run ${{ inputs.test_name }}
      if: ${{ startsWith(inputs.test_case, "tests_backbone") }}
      shell: bash -x +e {0}
      run: |
        cd transformers
        python -m pytest --ignore=tests/models/marian/test_modeling_marian.py -k backbone tests
    - name: Run ${{ inputs.test_name }}
      if: ${{ startsWith(inputs.test_case, "tests_py") }}
      shell: bash -x +e {0}
      run: |
        cd transformers
        python -m pytest tests/*.py
    - name: Run ${{ inputs.test_name }}
      if: ${{ startsWith(inputs.test_case, "tests_generation") }}
      shell: bash -x +e {0}
      run: |
        cd transformers
        python -m pytest tests/generation -k "not TestFSDPGeneration"
    - name: Run ${{ inputs.test_name }}
      if: ${{ startsWith(inputs.test_case, "tests_models") }}
      shell: bash -x +e {0}
      run: |
        cd transformers
        python -m pytest tests/models \
                --ignore=tests/models/marian/test_modeling_marian.py \
                -k "not test_resize_embeddings_untied and not test_resize_tokens_embeddings"
    - name: Run tests_trainer
      if: ${{ startsWith(inputs.test_case, "tests_trainer") }}
      shell: bash -x +e {0}
      run: |
        cd transformers
        python -m pytest tests/trainer \
                -k "not ray and not TestTrainerDistributed and not TestTrainerDistributedXPU and not TestFSDPTrainer"
    - name: Run tests_utils
      if: ${{ startsWith(inputs.test_case, "tests_utils") }}
      shell: bash -x +e {0}
      run: |
        cd transformers
        python -m pytest --ignore=tests/utils/test_import_utils.py tests/utils -k "not test_load_img_url_timeout"
