name: Linux E2E Test

inputs:
  suite:
    required: true
    type: string
    default: 'huggingface'
    description: Dynamo benchmarks test suite. huggingface,timm_models,torchbench. Delimiter is comma
  dt:
    required: true
    type: string
    default: 'float32'
    description: Data precision of the test.float32,bfloat16,float16,amp_bf16,amp_fp16. Delimiter is comma
  mode:
    required: true
    type: string
    default: 'inference'
    description: inference,training. Delimiter is comma
  scenario:
    required: true
    type: string
    default: 'accuracy'
    description: accuracy,performance. Delimiter is comma
  overwrite_model_list:
    type: string
    default: 'true'
    description: 'Overwrite pytorch model lists with torch-xpu-ops .ci/benchmarks/ overlay'

runs:
  using: composite
  steps:
    - name: Check Python
      shell: bash -xe {0}
      run: |
        which python && python -V
        which pip && pip list
    - name: E2E Test (${{ inputs.suite }} ${{ inputs.dt }} ${{ inputs.mode }} ${{ inputs.scenario }})
      shell: bash -xe {0}
      run: |
        cd ./pytorch
        # prepare for E2E test
        rsync -avz --delete ${GITHUB_WORKSPACE}/.github/scripts/run_benchmarks/ ./run_benchmarks/
        if [ -n "${MODEL_ONLY_NAME}" ];then
          model_list_args=" --model-only ${MODEL_ONLY_NAME} "
        fi
        if [ "${{ inputs.overwrite_model_list }}" == "true" ];then
          # overlay torch-xpu-ops model lists for nightly / PR tests
          rsync -avz ${GITHUB_WORKSPACE}/.ci/benchmarks/ benchmarks/dynamo/
          model_list_args=" --model-only benchmarks/dynamo/model_list.csv "
        fi
        rm -rf inductor_log torch
        python -m run_benchmarks --suite ${{ inputs.suite }} --dtype ${{ inputs.dt }} \
            --mode ${{ inputs.mode }} --scenario ${{ inputs.scenario }} ${model_list_args} \
            2>&1 |tee inductor_log/e2e_test.log || true
