import os
import sys

skip_list = (
    # Known issue
    "test_compare_cpu__refs_rsub_xpu_bfloat16",
    "test_compare_cpu_add_xpu_bfloat16",
    "test_compare_cpu_cumsum_xpu_bfloat16",
    "test_compare_cpu_cumsum_xpu_float16",
    "test_compare_cpu_div_floor_rounding_xpu_bfloat16",
    "test_compare_cpu_div_trunc_rounding_xpu_float16",
    "test_compare_cpu_index_add_xpu_bool",
    "test_compare_cpu_index_put_xpu_bool",
    "test_compare_cpu_log_xpu_complex64",
    "test_compare_cpu_mul_xpu_complex64",
    "test_compare_cpu_native_dropout_backward_xpu_bool",
    "test_compare_cpu_native_dropout_backward_xpu_int16",
    "test_compare_cpu_native_dropout_backward_xpu_int32",
    "test_compare_cpu_native_dropout_backward_xpu_int64",
    "test_compare_cpu_native_dropout_backward_xpu_int8",
    "test_compare_cpu_native_dropout_backward_xpu_uint8",
    "test_compare_cpu_pow_xpu_complex128",
    "test_compare_cpu_pow_xpu_complex64",
    "test_compare_cpu_rsqrt_xpu_bfloat16",
    "test_compare_cpu_sub_xpu_bfloat16",
    "test_compare_cpu_tanh_xpu_complex128",
    "test_compare_cpu_tanh_xpu_complex64",
    "test_non_standard_bool_values_native_dropout_backward_xpu_bool",


    # No supported
    "test_compare_cpu__refs_rsub_xpu_bool",
    "test_compare_cpu_abs_xpu_bool",
    "test_compare_cpu_arange_xpu_bool",
    "test_compare_cpu_arange_xpu_complex128",
    "test_compare_cpu_arange_xpu_complex64",
    "test_compare_cpu_bitwise_and_xpu_bfloat16",
    "test_compare_cpu_bitwise_and_xpu_complex128",
    "test_compare_cpu_bitwise_and_xpu_complex64",
    "test_compare_cpu_bitwise_and_xpu_float16",
    "test_compare_cpu_bitwise_and_xpu_float32",
    "test_compare_cpu_bitwise_and_xpu_float64",
    "test_compare_cpu_bitwise_not_xpu_bfloat16",
    "test_compare_cpu_bitwise_not_xpu_complex128",
    "test_compare_cpu_bitwise_not_xpu_complex64",
    "test_compare_cpu_bitwise_not_xpu_float16",
    "test_compare_cpu_bitwise_not_xpu_float32",
    "test_compare_cpu_bitwise_not_xpu_float64",
    "test_compare_cpu_bitwise_or_xpu_bfloat16",
    "test_compare_cpu_bitwise_or_xpu_complex128",
    "test_compare_cpu_bitwise_or_xpu_complex64",
    "test_compare_cpu_bitwise_or_xpu_float16",
    "test_compare_cpu_bitwise_or_xpu_float32",
    "test_compare_cpu_bitwise_or_xpu_float64",
    "test_compare_cpu_bitwise_xor_xpu_bfloat16",
    "test_compare_cpu_bitwise_xor_xpu_complex128",
    "test_compare_cpu_bitwise_xor_xpu_complex64",
    "test_compare_cpu_bitwise_xor_xpu_float16",
    "test_compare_cpu_bitwise_xor_xpu_float32",
    "test_compare_cpu_bitwise_xor_xpu_float64",
    "test_compare_cpu_clamp_max_xpu_complex128",
    "test_compare_cpu_clamp_max_xpu_complex64",
    "test_compare_cpu_clamp_min_xpu_complex128",
    "test_compare_cpu_clamp_min_xpu_complex64",
    "test_compare_cpu_clamp_xpu_bool",
    "test_compare_cpu_clamp_xpu_complex128",
    "test_compare_cpu_clamp_xpu_complex64",
    "test_compare_cpu_cumsum_xpu_bool",
    "test_compare_cpu_div_floor_rounding_xpu_bool",
    "test_compare_cpu_div_floor_rounding_xpu_complex128",
    "test_compare_cpu_div_floor_rounding_xpu_complex64",
    "test_compare_cpu_div_trunc_rounding_xpu_bool",
    "test_compare_cpu_div_trunc_rounding_xpu_complex128",
    "test_compare_cpu_div_trunc_rounding_xpu_complex64",
    "test_compare_cpu_fmod_xpu_bool",
    "test_compare_cpu_fmod_xpu_complex128",
    "test_compare_cpu_fmod_xpu_complex64",
    "test_compare_cpu_gcd_xpu_bfloat16",
    "test_compare_cpu_gcd_xpu_bool",
    "test_compare_cpu_gcd_xpu_complex128",
    "test_compare_cpu_gcd_xpu_complex64",
    "test_compare_cpu_gcd_xpu_float16",
    "test_compare_cpu_gcd_xpu_float32",
    "test_compare_cpu_gcd_xpu_float64",
    "test_compare_cpu_ge_xpu_complex128",
    "test_compare_cpu_ge_xpu_complex64",
    "test_compare_cpu_gt_xpu_complex128",
    "test_compare_cpu_gt_xpu_complex64",
    "test_compare_cpu_le_xpu_complex128",
    "test_compare_cpu_le_xpu_complex64",
    "test_compare_cpu_lt_xpu_complex128",
    "test_compare_cpu_lt_xpu_complex64",
    "test_compare_cpu_maximum_xpu_complex128",
    "test_compare_cpu_maximum_xpu_complex64",
    "test_compare_cpu_minimum_xpu_complex128",
    "test_compare_cpu_minimum_xpu_complex64",
    "test_compare_cpu_native_dropout_backward_xpu_complex128",
    "test_compare_cpu_native_dropout_backward_xpu_complex64",
    "test_compare_cpu_neg_xpu_bool",
    "test_compare_cpu_nn_functional_adaptive_avg_pool2d_xpu_bool",
    "test_compare_cpu_nn_functional_adaptive_avg_pool2d_xpu_complex128",
    "test_compare_cpu_nn_functional_adaptive_avg_pool2d_xpu_complex64",
    "test_compare_cpu_nn_functional_adaptive_avg_pool2d_xpu_int16",
    "test_compare_cpu_nn_functional_adaptive_avg_pool2d_xpu_int32",
    "test_compare_cpu_nn_functional_adaptive_avg_pool2d_xpu_int64",
    "test_compare_cpu_nn_functional_adaptive_avg_pool2d_xpu_int8",
    "test_compare_cpu_nn_functional_adaptive_avg_pool2d_xpu_uint8",
    "test_compare_cpu_nn_functional_threshold_xpu_bool",
    "test_compare_cpu_nn_functional_threshold_xpu_complex128",
    "test_compare_cpu_nn_functional_threshold_xpu_complex64",
    "test_compare_cpu_pow_xpu_bool",
    "test_compare_cpu_remainder_xpu_bool",
    "test_compare_cpu_remainder_xpu_complex128",
    "test_compare_cpu_remainder_xpu_complex64",
    "test_compare_cpu_sub_xpu_bool",
    "test_compare_cpu_view_as_complex_xpu_bfloat16",
    "test_compare_cpu_view_as_complex_xpu_bool",
    "test_compare_cpu_view_as_complex_xpu_complex128",
    "test_compare_cpu_view_as_complex_xpu_complex64",
    "test_compare_cpu_view_as_complex_xpu_int16",
    "test_compare_cpu_view_as_complex_xpu_int32",
    "test_compare_cpu_view_as_complex_xpu_int64",
    "test_compare_cpu_view_as_complex_xpu_int8",
    "test_compare_cpu_view_as_complex_xpu_uint8",
    "test_compare_cpu_view_as_real_xpu_bfloat16",
    "test_compare_cpu_view_as_real_xpu_bool",
    "test_compare_cpu_view_as_real_xpu_float16",
    "test_compare_cpu_view_as_real_xpu_float32",
    "test_compare_cpu_view_as_real_xpu_float64",
    "test_compare_cpu_view_as_real_xpu_int16",
    "test_compare_cpu_view_as_real_xpu_int32",
    "test_compare_cpu_view_as_real_xpu_int64",
    "test_compare_cpu_view_as_real_xpu_int8",
    "test_compare_cpu_view_as_real_xpu_uint8",

    # Align CUDA implementation. And the case is not enabled on CUDA.
    "test_compare_cpu_scatter_xpu_bool",
)


skip_options = " -k 'not " + skip_list[0]
for skip_case in skip_list[1:]:
    skip_option = " and not " + skip_case
    skip_options += skip_option
skip_options += "'"

test_command = "PYTORCH_TEST_WITH_SLOW=1 pytest -v test_ops_xpu.py"
test_command += skip_options

res = os.system(test_command)
exit_code = os.WEXITSTATUS(res)
sys.exit(exit_code)
