name: inductor-xpu-e2e-test

inputs:
  suite:
    required: true
    type: string
    default: 'huggingface'
    description: Dynamo benchmarks test suite. huggingface,timm_models,torchbench. Delimiter is comma
  env_prepare:
    required: false
    description: If set to any value, will prepare suite test env
  dt:
    required: true
    type: string
    default: 'float32'
    description: Data precision of the test.float32,int8. Delimiter is comma
  mode:
    required: true
    type: string
    default: 'inference'
    description: inference. Delimiter is comma
  scenario:
    required: true
    type: string
    default: 'accuracy'
    description: accuracy,performance. Delimiter is comma
  cards:
    required: false
    type: string
    default: 'all'
    description: which cards can be used in the test
  hf_token:
    required: false
    description: HUGGING_FACE_HUB_TOKEN for torchbench test
  pytorch:
    required: false
    type: string
    default: 'main'
    description: Pytorch branch/commit
  driver:
    required: false
    type: string
    default: 'lts'
    description: Driver lts/rolling

runs:
  using: composite
  steps:
    - name: Prepare ENV
      if: ${{ inputs.env_prepare }}
      shell: bash
      run: |
        source activate e2e_ci
        source .github/scripts/env.sh ${{ inputs.pytorch }}
        # accuracy code
        if [[ "${{ inputs.scenario }}" == *"accuracy"* ]];then
          cd ../ && rm -rf pt2e-accuracy && git clone -b yifeng/accuracy https://github.com/chuanqi129/inductor-tools
        fi
        # performance code
        if [[ "${{ inputs.scenario }}" == *"performance"* ]];then
          cd ../ && rm -rf pt2e-performance && git clone -b yifeng/pt2e_xpu https://github.com/zxd1997066/benchmark
        fi
        # deps
        if [[ ${{ inputs.scenario }} == *"performance"* ]]; then
          pip install pyyaml
          if [ "${{ inputs.pytorch }}" != "nightly_wheel" ]; then
            cd ../ && rm -rf audio && git clone --single-branch -b main https://github.com/pytorch/audio.git
            cd audio && git checkout $TORCHAUDIO_COMMIT_ID
            python setup.py bdist_wheel && pip uninstall torchaudio -y && pip install --no-deps dist/*.whl
            cd ../ && rm -rf vision && git clone --single-branch -b main https://github.com/pytorch/vision.git
            cd vision && git checkout $TORCHVISION_COMMIT_ID
            python setup.py bdist_wheel && pip uninstall torchvision -y && pip install --no-deps dist/*.whl
          fi
          # torchbench
          cd ../ && python -c "import torch, torchvision, torchaudio"
          rm -rf benchmark && git clone https://github.com/pytorch/benchmark.git
          cd benchmark && git checkout $TORCHBENCH_COMMIT_ID && pip install --no-deps -r requirements.txt
          python install.py --continue_on_fail
          # deps for torchrec_dlrm
          pip install pyre_extensions
          pip install fbgemm-gpu --index-url https://download.pytorch.org/whl/nightly/cpu
          pip install torchmetrics==1.0.3
          pip install torchrec --no-deps --index-url https://download.pytorch.org/whl/nightly/cpu
          # transformers
          pip install --force-reinstall git+https://github.com/huggingface/transformers@${TRANSFORMERS_VERSION}
          # timm
          pip install --no-deps git+https://github.com/huggingface/pytorch-image-models@$TIMM_COMMIT_ID
          pip install $(curl -sSL https://raw.githubusercontent.com/huggingface/pytorch-image-models/$TIMM_COMMIT_ID/requirements.txt | grep -vE torch)
        fi
        pip install numpy==1.26.4
    - name: E2E Test (${{ inputs.suite }} ${{ inputs.dt }} ${{ inputs.mode }} ${{ inputs.scenario }})
      env:
        HUGGING_FACE_HUB_TOKEN: ${{ inputs.hf_token }}
        NEOReadDebugKeys: ${{ inputs.driver == 'rolling' && '1' || '0' }}
        DisableScratchPages: ${{ inputs.driver == 'rolling' && '1' || '0' }}
      shell: bash
      run: |
        source activate e2e_ci
        source .github/scripts/env.sh ${{ inputs.pytorch }}
        cd ..
        pt2e_logs_dir="${{ github.workspace }}/../pytorch/inductor_log"
        rm -rf "${pt2e_logs_dir}" && mkdir -p "${pt2e_logs_dir}"
        if [[ "${{ inputs.scenario }}" == *"accuracy"* ]];then
          if [[ "${{ inputs.dt }}" == *"float32"* ]];then
            python pt2e-accuracy/scripts/modelbench/quant/inductor_quant_acc.py --device xpu --is_fp32 |\
                    tee "${pt2e_logs_dir}/accuracy-fp32.log"
          fi
          if [[ "${{ inputs.dt }}" == *"int8"* ]];then
            python pt2e-accuracy/scripts/modelbench/quant/inductor_quant_acc.py --device xpu |\
                    tee "${pt2e_logs_dir}/accuracy-int8.log"
          fi
        fi
        if [[ "${{ inputs.scenario }}" == *"performance"* ]];then
          models="alexnet,demucs,dlrm,hf_Albert,hf_Bert,hf_Bert_large,hf_DistilBert,hf_Roberta_base,mnasnet1_0,mobilenet_v2,"
          models+="mobilenet_v3_large,nvidia_deeprecommender,pytorch_CycleGAN_and_pix2pix,resnet152,resnet18,resnet50,resnext50_32x4d,"
          models+="shufflenet_v2_x1_0,squeezenet1_1,Super_SloMo,timm_efficientnet,timm_nfnet,timm_regnet,timm_resnest,"
          models+="timm_vision_transformer,timm_vision_transformer_large,timm_vovnet,vgg16"
          if [[ "${{ inputs.dt }}" == *"float32"* ]];then
            python run_benchmark.py xpu --test eval --channels-last --metrics throughputs --torchdynamo inductor -m $models
          fi
          if [[ "${{ inputs.dt }}" == *"float32"* ]];then
            python run_benchmark.py xpu --test eval --channels-last --metrics throughputs --torchdynamo inductor --quantization pt2e -m $models
          fi
        fi
