name: inductor-xpu-pt2e-test

inputs:
  dt:
    required: true
    type: string
    default: 'float32'
    description: Data precision of the test.float32,int8. Delimiter is comma
  scenario:
    required: true
    type: string
    default: 'accuracy'
    description: accuracy,performance. Delimiter is comma
  pytorch:
    required: false
    type: string
    default: 'main'
    description: Pytorch branch/commit

runs:
  using: composite
  steps:
    - name: Check Python
      shell: bash -xe {0}
      run: |
        which python && python -V
        which pip && pip list
    - name: Prepare dataset
      shell: bash -xe {0}
      run: |
        # dataset
        dataset_dir="${RUNNER_TEMP}/_datasets/imagenet"
        if [ ! -d ${dataset_dir} ];then
          rm -rf ${dataset_dir} && mkdir -p ${dataset_dir} && cd ${dataset_dir}
          wget -O valprep.sh https://raw.githubusercontent.com/soumith/imagenetloader.torch/master/valprep.sh
          wget -q https://image-net.org/data/ILSVRC/2012/ILSVRC2012_img_val.tar
          tar -xf ILSVRC2012_img_val.tar
          bash valprep.sh
        fi
        echo "dataset_dir=${dataset_dir}" >> ${GITHUB_ENV}
    - name: PT2E Test (${{ inputs.dt }}  ${{ inputs.scenario }})
      shell: bash -xe {0}
      run: |
        # prepare for PT2E test
        rm -rf inductor_log
        rsync -avz --delete ${GITHUB_WORKSPACE}/.github/scripts/run_benchmarks/ ./run_pt2e/
        cd ./run_pt2e
        if [ -n "${MODEL_ONLY_NAME}" ];then
          model_list_args=" --model-only ${MODEL_ONLY_NAME} "
        else
          model_list_args=" --model-only ${GITHUB_WORKSPACE}/.ci/benchmarks/model_list.csv "
        fi
        python -m run_pt2e --suite pt2e --mode inference \
            --dtype ${{ inputs.dt }} --scenario ${{ inputs.scenario }} \
            --dataset-dir ${dataset_dir} ${model_list_args} \
            2>&1 |tee inductor_log/run_pt2e.log || true
        rsync -avz --delete inductor_log/ ${GITHUB_WORKSPACE}/pytorch/inductor_log/
