# Copyright (c) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

# Default header applied to all files unless specified otherwise
default_header: |
  Copyright 2020-2025 Intel Corporation

  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

# Files/patterns to exclude from processing entirely
exclude:
  - ".git/*"
  - "__pycache__/*"
  - ".ci/**/*"
  - ".github/**/*"
  - "yaml/**/*"
  - "tools/**/*"
  - "**/__init__.py"
  - "lint/**/*"
  - "src/ATen/native/xpu/sycl/Philox4x32.h" #TODO: Remove after https://github.com/intel/torch-xpu-ops/issues/2485 is closed
