skip_dict = {
    # SYCL default context is not supported on Windows
    "test_tensor_creation_ops_xpu.py": (
        "test_alias_from_dlpack_xpu_bfloat16",
        "test_alias_from_dlpack_xpu_complex128",
        "test_alias_from_dlpack_xpu_complex64",
        "test_alias_from_dlpack_xpu_float16",
        "test_alias_from_dlpack_xpu_float32",
        "test_alias_from_dlpack_xpu_float64",
        "test_alias_from_dlpack_xpu_int16",
        "test_alias_from_dlpack_xpu_int32",
        "test_alias_from_dlpack_xpu_int64",
        "test_alias_from_dlpack_xpu_int8",
        "test_alias_from_dlpack_xpu_uint8",
        "test_copy_from_dlpack_xpu_bfloat16",
        "test_copy_from_dlpack_xpu_complex128",
        "test_copy_from_dlpack_xpu_complex64",
        "test_copy_from_dlpack_xpu_float16",
        "test_copy_from_dlpack_xpu_float32",
        "test_copy_from_dlpack_xpu_float64",
        "test_copy_from_dlpack_xpu_int16",
        "test_copy_from_dlpack_xpu_int32",
        "test_copy_from_dlpack_xpu_int64",
        "test_copy_from_dlpack_xpu_int8",
        "test_copy_from_dlpack_xpu_uint8",
    ),
    # SYCL compiler issue where host and device results differ for math ops with complex dtypes
    "test_unary_ufuncs_xpu.py": None,
    "functorch/test_ops_functorch_xpu.py": None,
}
