skip_dict = {
    "../../../../test/distributed/fsdp/test_checkpoint_wrapper.py": None,
    "../../../../test/distributed/fsdp/test_distributed_checkpoint.py": None,
    "../../../../test/distributed/fsdp/test_fsdp_apply.py": None,
    "../../../../test/distributed/fsdp/test_fsdp_backward_prefetch.py": None,
    "../../../../test/distributed/fsdp/test_fsdp_checkpoint.py": None,
    "../../../../test/distributed/fsdp/test_fsdp_clip_grad_norm.py": None,
    "../../../../test/distributed/fsdp/test_fsdp_comm.py": None,
    "../../../../test/distributed/fsdp/test_fsdp_comm_hooks.py": None,
    "../../../../test/distributed/fsdp/test_fsdp_core.py": None,
    "../../../../test/distributed/fsdp/test_fsdp_dtensor_state_dict.py": None,
    "../../../../test/distributed/fsdp/test_fsdp_exec_order.py": None,
    "../../../../test/distributed/fsdp/test_fsdp_fine_tune.py": None,
    "../../../../test/distributed/fsdp/test_fsdp_flatten_params.py": None,
    "../../../../test/distributed/fsdp/test_fsdp_freezing_weights.py": None,
    "../../../../test/distributed/fsdp/test_fsdp_fx.py": None,
    "../../../../test/distributed/fsdp/test_fsdp_grad_acc.py": None,
    "../../../../test/distributed/fsdp/test_fsdp_hybrid_shard.py": None,
    "../../../../test/distributed/fsdp/test_fsdp_ignored_modules.py": None,
    "../../../../test/distributed/fsdp/test_fsdp_input.py": None,
    "../../../../test/distributed/fsdp/test_fsdp_memory.py": None,
    "../../../../test/distributed/fsdp/test_fsdp_meta.py": None,
    "../../../../test/distributed/fsdp/test_fsdp_misc.py": (
        # fsdp accuracy gaps
        # https://github.com/intel/torch-xpu-ops/issues/1504, Performance test, should skip
        "test_fsdp_optimizer_overlap",
    ),
    "../../../../test/distributed/fsdp/test_fsdp_mixed_precision.py": None,
    "../../../../test/distributed/fsdp/test_fsdp_multiple_forward.py": None,
    "../../../../test/distributed/fsdp/test_fsdp_multiple_wrapping.py": None,
    "../../../../test/distributed/fsdp/test_fsdp_optim_state.py": None,
    "../../../../test/distributed/fsdp/test_fsdp_pure_fp16.py": None,
    "../../../../test/distributed/fsdp/test_fsdp_sharded_grad_scaler.py": None,
    "../../../../test/distributed/fsdp/test_fsdp_state_dict.py": None,
    "../../../../test/distributed/fsdp/test_fsdp_tp_integration.py": None,
    "../../../../test/distributed/fsdp/test_fsdp_traversal.py": None,
    "../../../../test/distributed/fsdp/test_fsdp_uneven.py": None,
    "../../../../test/distributed/fsdp/test_fsdp_unshard_params.py": None,
    "../../../../test/distributed/fsdp/test_fsdp_use_orig_params.py": None,
    "../../../../test/distributed/fsdp/test_hsdp_dtensor_state_dict.py": None,
    "../../../../test/distributed/fsdp/test_shard_utils.py": None,
    "../../../../test/distributed/fsdp/test_utils.py": None,
    "../../../../test/distributed/fsdp/test_wrap.py": None,
    "../../../../test/distributed/test_backends.py": None,
    "../../../../test/distributed/test_c10d_common.py": None,
    "../../../../test/distributed/test_c10d_logger.py": None,
    "../../../../test/distributed/test_c10d_object_collectives.py": None,
    "../../../../test/distributed/test_compute_comm_reordering.py": None,
    "../../../../test/distributed/test_control_collectives.py": None,
    "../../../../test/distributed/test_device_mesh.py": None,
    "../../../../test/distributed/test_dynamo_distributed.py": None,
    "../../../../test/distributed/test_fake_pg.py": None,
    "../../../../test/distributed/test_functional_api.py": None,
    "../../../../test/distributed/test_inductor_collectives.py": None,
    "../../../../test/distributed/test_multi_threaded_pg.py": None,
    "../../../../test/distributed/test_store.py": None,
    "../../../../test/distributed/pipelining/test_backward.py": None,
    "../../../../test/distributed/pipelining/test_microbatch.py": None,
    "../../../../test/distributed/pipelining/test_pipe.py": None,
    "../../../../test/distributed/pipelining/test_schedule.py": None,
    "../../../../test/distributed/pipelining/test_transformer.py": None,
    "../../../../test/distributed/pipelining/test_unflatten.py": None,
    "../../../../test/distributed/tensor/parallel/test_micro_pipeline_tp.py": None,
    "../../../../test/distributed/tensor/parallel/test_tp_examples.py": None,
    "../../../../test/distributed/tensor/parallel/test_tp_random_state.py": None,
    "../../../../test/distributed/tensor/parallel/test_parallelize_api.py": None,
    "../../../../test/distributed/tensor/parallel/test_tp_style.py": None,
    "../../../../test/distributed/tensor/test_api.py": None,
    "../../../../test/distributed/tensor/test_attention.py": None,
    "../../../../test/distributed/tensor/test_common_rules.py": None,
    "../../../../test/distributed/tensor/test_dtensor.py": None,
    "../../../../test/distributed/tensor/test_dtensor_compile.py": None,
    "../../../../test/distributed/tensor/test_experimental_ops.py": None,
    "../../../../test/distributed/tensor/test_init.py": None,
    "../../../../test/distributed/tensor/test_math_ops.py": None,
    "../../../../test/distributed/tensor/test_random_ops.py": None,
    "../../../../test/distributed/tensor/test_redistribute.py": None,
    "../../../../test/distributed/tensor/test_tensor_ops.py": None,
    "../../../../test/distributed/tensor/experimental/test_register_sharding.py": None,
    "../../../../test/distributed/_composable/fsdp/test_fully_shard_autograd.py": None,
    "../../../../test/distributed/_composable/fsdp/test_fully_shard_clip_grad_norm_.py": None,
    "../../../../test/distributed/_composable/fsdp/test_fully_shard_comm.py": (
        # ValueError: Cannot use ReduceOp.PREMUL_SUM with XCCL 
        # https://github.com/intel/torch-xpu-ops/issues/1571, 2.8 skipped
        "test_set_reduce_scatter_divide_factor",
    ),
    "../../../../test/distributed/_composable/fsdp/test_fully_shard_compile.py": None,
    "../../../../test/distributed/_composable/fsdp/test_fully_shard_extensions.py": None,
    "../../../../test/distributed/_composable/fsdp/test_fully_shard_frozen.py": None,
    "../../../../test/distributed/_composable/fsdp/test_fully_shard_grad_scaler.py": None,
    "../../../../test/distributed/_composable/fsdp/test_fully_shard_ignore_params.py": None,
    "../../../../test/distributed/_composable/fsdp/test_fully_shard_init.py": None,
    "../../../../test/distributed/_composable/fsdp/test_fully_shard_logging.py": None,
    "../../../../test/distributed/_composable/fsdp/test_fully_shard_memory.py": None,
    "../../../../test/distributed/_composable/fsdp/test_fully_shard_mixed_precision.py": None,
    "../../../../test/distributed/_composable/fsdp/test_fully_shard_overlap.py": (
        # Performance test, should skip
        "test_fully_shard_training_overlap",
    ),
    "../../../../test/distributed/_composable/fsdp/test_fully_shard_state_dict.py": None,
    "../../../../test/distributed/_composable/fsdp/test_fully_shard_state.py": None,
    "../../../../test/distributed/_composable/fsdp/test_fully_shard_training.py": None,
    "../../../../test/distributed/_composable/test_replicate_with_compiler.py": None,
    "../../../../test/distributed/_shard/test_sharder.py": None,
    "../../../../test/distributed/_shard/sharded_tensor/test_logger.py": None,
    "../../../../test/distributed/_shard/sharded_tensor/test_sharded_tensor.py": None,
    "../../../../test/distributed/_shard/sharded_tensor/test_sharded_tensor_reshard.py": None,
    "../../../../test/distributed/_shard/sharding_plan/test_sharding_plan.py": None,
    "../../../../test/distributed/_shard/sharding_spec/test_sharding_spec.py": None,
    "../../../../test/distributed/_tools/test_fsdp2_mem_tracker.py": None,
    "../../../../test/distributed/_tools/test_mem_tracker.py": None,
    "../../../../test/distributed/_tools/test_memory_tracker.py": None,
    "../../../../test/distributed/_tools/test_mod_tracker.py": None,
    "../../../../test/distributed/checkpoint/e2e/test_e2e_save_and_load.py": None,
    "../../../../test/distributed/checkpoint/e2e/test_fine_tuning.py": None,
    "../../../../test/distributed/checkpoint/e2e/test_fsdp_ep.py": None,
    "../../../../test/distributed/checkpoint/fsdp/test_fsdp_dsd.py": None,
    "../../../../test/distributed/checkpoint/test_checkpoint.py": None,
    "../../../../test/distributed/checkpoint/test_compatibility.py": None,
    "../../../../test/distributed/checkpoint/test_dedup_tensors.py": None,
    "../../../../test/distributed/checkpoint/test_dtensor_checkpoint.py": None,
    "../../../../test/distributed/checkpoint/test_dtensor_resharding.py": None,
    "../../../../test/distributed/checkpoint/test_file_system_checkpoint.py": None,
    "../../../../test/distributed/checkpoint/test_file_system_checkpoint_cpu.py": None,
    "../../../../test/distributed/checkpoint/test_format_utils.py": None,
    "../../../../test/distributed/checkpoint/test_fsdp_model_state.py": None,
    "../../../../test/distributed/checkpoint/test_fsdp_optim_state.py": None,
    "../../../../test/distributed/checkpoint/test_fsdp_tp_checkpoint_conversion.py": None,
    "../../../../test/distributed/checkpoint/test_fsspec.py": None,
    "../../../../test/distributed/checkpoint/test_hsdp_checkpoint.py": None,
    "../../../../test/distributed/checkpoint/test_nested_dict.py": None,
    "../../../../test/distributed/checkpoint/test_planner.py": None,
    "../../../../test/distributed/checkpoint/test_save_load_api.py": None,
    "../../../../test/distributed/checkpoint/test_state_dict.py": None,
    "../../../../test/distributed/checkpoint/test_state_dict_utils.py": None,
    "../../../../test/distributed/checkpoint/test_tp_checkpoint.py": None,
    "../../../../test/distributed/checkpoint/test_traverse.py": None,
    "../../../../test/distributed/checkpoint/test_utils.py": None,
    "../../../../test/distributed/checkpoint/_experimental/test_barriers.py": None,
    "../../../../test/distributed/checkpoint/_experimental/test_builder.py": None,
    "../../../../test/distributed/checkpoint/_experimental/test_checkpoint_process.py": None,
    "../../../../test/distributed/checkpoint/_experimental/test_checkpoint_reader.py": None,
    "../../../../test/distributed/checkpoint/_experimental/test_checkpoint_writer.py": None,
    "../../../../test/distributed/checkpoint/_experimental/test_checkpointer.py": None,
    "../../../../test/distributed/checkpoint/_experimental/test_staging.py": None,
    "../../../../test/distributed/checkpoint/_experimental/test_types.py": None,
    "../../../../test/distributed/elastic/events/lib_test.py": None,
    "../../../../test/distributed/elastic/metrics/api_test.py": None,
    "../../../../test/distributed/elastic/multiprocessing/api_test.py": None,
    "../../../../test/distributed/elastic/test_control_plane.py": (
        # https://github.com/intel/torch-xpu-ops/issues/1871 same failure on cuda
        "test_tcp",
    ),
    "../../../../test/distributed/elastic/timer/api_test.py": None,
    "../../../../test/distributed/elastic/timer/local_timer_example.py": None,
    "../../../../test/distributed/elastic/timer/local_timer_test.py": None,
    "../../../../test/distributed/elastic/utils/distributed_test.py": None,
    "../../../../test/distributed/elastic/utils/logging_test.py": None,
    "../../../../test/distributed/elastic/utils/util_test.py": None,
    "../../../../test/distributed/optim/test_apply_optimizer_in_backward.py": None,
    "../../../../test/distributed/optim/test_named_optimizer.py": None,
    "../../../../test/distributed/optim/test_zero_redundancy_optimizer.py": None,
    "distributed/test_c10d_ops_xccl.py": None,
    "distributed/test_c10d_xccl.py": None,
    "../../../../test/distributed/test_c10d_functional_native.py": None,
    # "../../../../test/distributed/pipelining/test_stage.py": None,
    "../../../../test/distributed/pipelining/test_transformer.py": None,
    "../../../../test/distributed/_composable/test_contract.py": None,
    "../../../../test/distributed/_composable/test_replicate_mixed_precision.py": None,
    "../../../../test/distributed/_composable/test_replicate_training.py": None,
    "../../../../test/distributed/_composable/test_replicate_with_fsdp.py": None,
    "../../../../test/distributed/_shard/sharded_optim/test_sharded_optim.py": None,
    "../../../../test/distributed/_shard/sharded_tensor/ops/test_binary_cmp.py": None,
    "../../../../test/distributed/_shard/sharded_tensor/ops/test_embedding.py": None,
    "../../../../test/distributed/_shard/sharded_tensor/ops/test_embedding_bag.py": None,
    "../../../../test/distributed/_shard/sharded_tensor/ops/test_init.py": None,
    "../../../../test/distributed/_shard/sharded_tensor/ops/test_tensor_ops.py": None,
    "../../../../test/distributed/_shard/sharding_plan/test_sharding_plan.py": None,
    "../../../../test/distributed/_shard/sharding_spec/test_sharding_spec.py": None,
    "../../../../test/distributed/_tools/test_fake_collectives.py": None,
    "../../../../test/distributed/_tools/test_runtime_estimator.py": None,
    "../../../../test/distributed/_tools/test_sac_estimator.py": None,
    "../../../../test/distributed/_tools/test_sac_ilp.py": None,
}

skip_dict_python = {
    "../../../../test/distributed/test_c10d_functional_native.py": None,
    # "../../../../test/distributed/pipelining/test_schedule_multiproc.py": None,  # Hang error.
    # "../../../../test/distributed/pipelining/test_stage.py": None,
    "../../../../test/distributed/pipelining/test_transformer.py": None,
}
