skip_dict = {
    "test_binary_ufuncs_xpu": (
        "test_batch_vs_slicing___rpow___xpu_complex64",
        "test_batch_vs_slicing__refs_pow_xpu_complex64",
        "test_batch_vs_slicing_pow_xpu_complex64",
        "test_contig_size1___rpow___xpu_complex64",
        "test_contig_size1__refs_pow_xpu_complex64",
        "test_contig_size1_large_dim___rpow___xpu_complex64",
        "test_contig_size1_large_dim__refs_pow_xpu_complex64",
        "test_contig_size1_large_dim_pow_xpu_complex32",
        "test_contig_size1_large_dim_pow_xpu_complex64",
        "test_contig_size1_pow_xpu_complex32",
        "test_contig_size1_pow_xpu_complex64",
        "test_contig_vs_every_other___rpow___xpu_complex64",
        "test_contig_vs_every_other__refs_pow_xpu_complex64",
        "test_contig_vs_every_other_pow_xpu_complex32",
        "test_contig_vs_every_other_pow_xpu_complex64",
        "test_contig_vs_transposed___rpow___xpu_complex64",
        "test_contig_vs_transposed__refs_pow_xpu_complex64",
        "test_contig_vs_transposed_pow_xpu_complex32",
        "test_contig_vs_transposed_pow_xpu_complex64",
        "test_non_contig___rpow___xpu_complex64",
        "test_non_contig__refs_pow_xpu_complex64",
        "test_non_contig_expand___rpow___xpu_complex64",
        "test_non_contig_expand__refs_pow_xpu_complex64",
        "test_non_contig_expand_pow_xpu_complex32",
        "test_non_contig_expand_pow_xpu_complex64",
        "test_non_contig_index___rpow___xpu_complex64",
        "test_non_contig_index__refs_pow_xpu_complex64",
        "test_non_contig_index_pow_xpu_complex32",
        "test_non_contig_index_pow_xpu_complex64",
        "test_non_contig_pow_xpu_complex64",
    ),
    "test_nn_xpu.py": ("test_adaptiveavg_pool1d_shmem_xpu",),
    "test_unary_ufuncs_xpu.py": None,
    "functorch/test_ops_functorch_xpu.py": None,
}
