# Copyright 2020-2025 Intel Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0

skip_dict = {
    "../../../../test/distributed/fsdp/test_fsdp_checkpoint.py": None,
    "../../../../test/distributed/fsdp/test_checkpoint_wrapper.py": None,
    "../../../../test/distributed/fsdp/test_fsdp_backward_prefetch.py": None,
    "../../../../test/distributed/fsdp/test_fsdp_apply.py": None,
    "../../../../test/distributed/fsdp/test_fsdp_clip_grad_norm.py": None,
    "../../../../test/distributed/fsdp/test_fsdp_comm.py": None,
    "../../../../test/distributed/fsdp/test_fsdp_comm_hooks.py": None,
    "../../../../test/distributed/fsdp/test_fsdp_core.py": (
        "test_transformer_no_grad_mixed_precision_True_xpu",
    ),
    "../../../../test/distributed/fsdp/test_fsdp_exec_order.py": None,
    "../../../../test/distributed/fsdp/test_fsdp_dtensor_state_dict.py": None,
    "../../../../test/distributed/fsdp/test_fsdp_flatten_params.py": None,
    "../../../../test/distributed/fsdp/test_fsdp_freezing_weights.py": None,
    "../../../../test/distributed/fsdp/test_fsdp_hybrid_shard.py": None,
    "../../../../test/distributed/fsdp/test_fsdp_ignored_modules.py": None,
    "../../../../test/distributed/fsdp/test_fsdp_memory.py": None,
    "../../../../test/distributed/fsdp/test_fsdp_meta.py": None,
    "../../../../test/distributed/fsdp/test_fsdp_misc.py": None,
    "../../../../test/distributed/fsdp/test_fsdp_overlap.py": None,
    "../../../../test/distributed/fsdp/test_fsdp_pure_fp16.py": None,
    "../../../../test/distributed/fsdp/test_fsdp_sharded_grad_scaler.py": None,
    "../../../../test/distributed/fsdp/test_fsdp_state_dict.py": None,
    "../../../../test/distributed/fsdp/test_fsdp_tp_integration.py": None,
    "../../../../test/distributed/fsdp/test_fsdp_traversal.py": None,
    "../../../../test/distributed/fsdp/test_fsdp_uneven.py": None,
    "../../../../test/distributed/fsdp/test_fsdp_unshard_params.py": None,
    "../../../../test/distributed/fsdp/test_fsdp_use_orig_params.py": (
        "test_diff_hyperparams_sharding_strategy_str_full_shard",
        "test_diff_hyperparams_sharding_strategy_str_shard_grad_op",
    ),
    "../../../../test/distributed/fsdp/test_hsdp_dtensor_state_dict.py": None,
    "../../../../test/distributed/fsdp/test_shard_utils.py": None,
    "../../../../test/distributed/fsdp/test_utils.py": None,
    "../../../../test/distributed/fsdp/test_wrap.py": None,
    "../../../../test/distributed/fsdp/test_fsdp_fine_tune.py": None,
    "../../../../test/distributed/fsdp/test_fsdp_fx.py": None,
    "../../../../test/distributed/fsdp/test_fsdp_input.py": None,
    "../../../../test/distributed/fsdp/test_fsdp_multiple_forward.py": None,
    "../../../../test/distributed/fsdp/test_fsdp_multiple_wrapping.py": None,
    "../../../../test/distributed/_composable/fsdp/test_fully_shard_clip_grad_norm_.py": None,
    "../../../../test/distributed/_composable/fsdp/test_fully_shard_comm.py": None,
    "../../../../test/distributed/_composable/fsdp/test_fully_shard_compile.py": (
        "test_compiled_autograd_ctx",
        "test_nested_fully_shard_backend_aot_eager",
        "test_nested_fully_shard_backend_aot_eager_decomp_partition",
        "test_nested_fully_shard_backend_inductor_fullgraph_True",
        "test_nested_fully_shard_backend_inductor_fullgraph_True_graph_partition",
        "test_simple_mlp_fullgraph_backend_aot_eager",
        "test_simple_mlp_fullgraph_backend_aot_eager_decomp_partition",
        "test_simple_mlp_fullgraph_backend_inductor",
        "test_transformer_backend_aot_eager",
        "test_transformer_backend_aot_eager_decomp_partition",
    ),
    "../../../../test/distributed/_composable/fsdp/test_fully_shard_frozen.py": None,
    "../../../../test/distributed/_composable/fsdp/test_fully_shard_mixed_precision.py": None,
    "../../../../test/distributed/_composable/fsdp/test_fully_shard_state_dict.py": (
        "test_cached_state_dict",
        "test_dp_state_dict_cpu_offload",
    ),
    "../../../../test/distributed/_composable/fsdp/test_fully_shard_training.py": (
        "test_explicit_prefetching",
        "test_multi_forward_module",
        "test_train_parity_single_group_shard_dim0",
        "test_train_parity_single_group_shard_largest_dim",
        "test_train_parity_shard_placement_fn_shard_largest_dim",
        "test_3d_mlp_with_nd_mesh",
    ),
    "../../../../test/distributed/_composable/test_composability/test_2d_composability.py": (
        "test_tp_with_fsdp_offloading",
    ),
    "../../../../test/distributed/_composable/test_replicate_with_compiler.py": None,
    "../../../../test/distributed/_composable/test_composability/test_pp_composability.py": None,
    "../../../../test/distributed/_composable/test_checkpoint.py": None,
    "../../../../test/distributed/_composable/test_contract.py": None,
    "distributed/test_c10d_xccl.py": None,
    "distributed/test_c10d_ops_xccl.py": None,
    "../../../../test/distributed/test_functional_api.py": None,
    "../../../../test/distributed/_tools/test_fsdp2_mem_tracker.py": None,
    "../../../../test/distributed/_tools/test_mem_tracker.py": None,
    "../../../../test/distributed/_tools/test_memory_tracker.py": None,
}
