
INTERNODE_DISPATCH_RDMA_SENDER_DEBUG=0 RING_WORLD_SIZE=2 RING_NUM_MAX_NVL_PEERS=1 NUM_TOKENS=4096 RING_NUM_MAX_TOKENS_PER_RANK=4096 RING_GPU_IDS="0 2" RING_NIC_IDS="0 2" bash test_ishmem_pairwise_throughput.sh


