name: Get Runner Infos

outputs:
  runner_id:
    value: ${{ steps.runner.outputs.runner_id }}
  user_id:
    value: ${{ steps.runner.outputs.user_id }}
  render_id:
    value: ${{ steps.runner.outputs.render_id }}
  hostname:
    value: ${{ steps.runner.outputs.hostname }}
  xpu_num:
    value: ${{ steps.runner.outputs.xpu_num }}
  cpus_per_xpu:
    value: ${{ steps.runner.outputs.cpus_per_xpu }}
  pytest_extra_args:
    value: ${{ steps.runner.outputs.pytest_extra_args }}

permissions: read-all

runs:
  using: composite
  steps:
    - name: Get runner
      shell: bash -xe {0}
      id: runner
      run: |
        # get test runner
        printenv
