name: Get Runner Infos

on:
  workflow_call:

outputs:
  test_host:
    value: ${{ steps.runner.outputs.test_host }}
  test_user:
    value: ${{ steps.runner.outputs.test_user }}
  test_group:
    value: ${{ steps.runner.outputs.test_group }}

permissions: read-all

runs:
  using: composite
  steps:
    - name: Get runner
      shell: bash -xe {0}
      id: runner
      run: |
        # get test runner
        echo "test_host=$(echo ${RUNNER_NAME} |sed 's/\-[0-9]$//')" |tee -a ${GITHUB_OUTPUT}
        echo "test_user=$(id -u)" |tee -a ${GITHUB_OUTPUT}
        echo "test_group=$(getent group render |cut -d: -f3)" |tee -a ${GITHUB_OUTPUT}
        # show host info
        lscpu
        lshw -C display
        free -h
        df -h
        cat /etc/os-release
        uname -a
    - name: Cleanup host
      if: ${{ always() }}
      shell: bash -xe {0}
      run: |
        # clean docker cache
        docker system prune -af || true
        # clean workspace
        ls -al
        sudo find ./ |grep -v "^\./$" |xargs sudo rm -rf
        cd ${RUNNER_WORKSPACE}/..
        if [ "${PWD}" != "/" ];then
          ls -al
          sudo chmod 777 -R torch-xpu-ops _temp _actions _tool || true
          sudo rm -rf _temp
        fi
