name: Git Bisect Search

on:
  workflow_dispatch:
    inputs:
      nodel_label:
        description: 'Which node to use'
        default: 'pvc_rolling'
        required: true
      search_type:
        description: 'Check type: accuracy or performance'
        required: true
      search_repo:
        description: 'Check type: pytorch=a/b,torch-xpu-ops=c/d'
        required: true

jobs:
  job_bisect:
    runs-on: ${{ inputs.nodel_label }}
    steps:
    - name: Cleanup workspace
      run: |
        rm -rf ./*
    - name: Checkout the repository
      uses: actions/checkout@v4

    - name: Set up Android SDK
      uses: android-actions/setup-android@v3.2.0


    - name: Resolve bad commit
      run: |
        if [[ -z "${{ github.event.inputs.bad_commit }}" ]]; then
          INIT_BAD_COMMIT_ID=$(git rev-parse HEAD)
        elif git rev-parse --verify --quiet ${{ github.event.inputs.bad_commit }}^{commit}; then
          INIT_BAD_COMMIT_ID=${{ github.event.inputs.bad_commit }}
        else
          echo "The specified bad commit is invalid."
          exit 1
        fi
        echo "INIT_BAD_COMMIT_ID=$INIT_BAD_COMMIT_ID" >> $GITHUB_ENV

    - name: Create the check script
      run: |
        # Trim leading and trailing '&&' and replace with a single newline character
        COMMANDS="${{ github.event.inputs.check_commands }}"
        COMMANDS="${COMMANDS##&&}"  # Remove leading &&
        COMMANDS="${COMMANDS%%&&}"  # Remove trailing &&
    
        # Split commands by '&&' and write to a script file
        IFS='&&' read -ra CMD_ARRAY <<< "$COMMANDS"
        for CMD in "${CMD_ARRAY[@]}"; do
          # Trim any leading and trailing whitespace from each command
          CMD="$(echo "$CMD" | xargs)"
          # Skip empty commands
          if [ -n "$CMD" ]; then
            echo "$CMD" >> bisect_check.sh
          fi
        done
        chmod +x bisect_check.sh

    - name: Check the good commit
      run: |
        if git checkout ${{ github.event.inputs.good_commit }}; then
          echo "The specified good commit:${{ github.event.inputs.good_commit }} is valid in git history" >> $GITHUB_STEP_SUMMARY
          # Run bisect check bash here, if it is not valid, exit 1 and print the error message
          if ! ./bisect_check.sh; then
            echo "The specified good commit:${{ github.event.inputs.good_commit }} is invalid in the check command, which means the input good commit is actually not good for your check command." >> $GITHUB_STEP_SUMMARY
            git checkout -
            exit 1
          else
            echo "The specified good commit:${{ github.event.inputs.good_commit }} is valid in the check command." >> $GITHUB_STEP_SUMMARY
            git checkout -
          fi
        else
          echo "The specified good commit:${{ github.event.inputs.good_commit }} is invalid in git history" >> $GITHUB_STEP_SUMMARY
          exit 1
        fi

    - name: Run bisect with check command bash
      run: |
        git bisect start
        git bisect bad $INIT_BAD_COMMIT_ID
        git bisect good ${{ github.event.inputs.good_commit }}
        BISECT_OUTPUT=$(git bisect run ./bisect_check.sh)
        echo "$BISECT_OUTPUT"
        FIRST_BAD_COMMIT=$(git rev-parse bisect/bad)
        git bisect log >> bisect_log.txt
        git bisect reset
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "## Bisect Log" >> $GITHUB_STEP_SUMMARY
        cat bisect_log.txt >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "## Bisect result" >> $GITHUB_STEP_SUMMARY
        if [[ -z "$FIRST_BAD_COMMIT" ]]; then
          echo "No bad commit found." 
          echo "No bad commit found." >> $GITHUB_STEP_SUMMARY
        else
          DIFF_URL="https://github.com/${{ github.event.inputs.org_repo }}/commit/${FIRST_BAD_COMMIT}"
          echo "FIRST_BAD_COMMIT=$FIRST_BAD_COMMIT" >> $GITHUB_ENV
          echo "FIRST_BAD_COMMIT: [$FIRST_BAD_COMMIT]($DIFF_URL)" >> $GITHUB_STEP_SUMMARY
          ERROR_LOG=$(echo "$BISECT_OUTPUT" | awk '/first bad commit: first commit that fails/{flag=1; next} /Bisecting:/{flag=0} flag')
          echo "### Error log:" >> $GITHUB_STEP_SUMMARY
          echo "$ERROR_LOG" >> $GITHUB_STEP_SUMMARY
        fi

    - name: Upload bisect_log.txt
      uses: actions/upload-artifact@v4.3.1
      with:
        name: bisect_log
        path: bisect_log.txt