name: Linux E2E Summary

on:
  workflow_call:
    inputs:
      test_type:
        type: string
        default: "build-cicd"
        description: Test type, default is for CI tests, others (build or wheel)-(nightly, weekly or ondemand)
      python:
        type: string
        default: '3.10'
        description: Python version

permissions:
  contents: read

defaults:
  run:
    shell: bash -xe {0}

jobs:
  summary:
    runs-on: ubuntu-24.04
    permissions:
      actions: read
      contents: read
      issues: write
      pull-requests: write
    env:
      GH_TOKEN: ${{ github.token }}
      REFERENCE_ISSUE_ID: 1645
      AGENT_TOOLSDIRECTORY: /tmp/xpu-tool
    steps:
      - name: Checkout torch-xpu-ops
        uses: actions/checkout@v4
      - name: Setup python-${{ inputs.python }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python }}
      - name: Install gh-cli
        run: |
          sudo apt-get update
          sudo apt-get install gh rsync ca-certificates -y
          pip install pandas requests pygithub
      - name: Download Target Artifact
        run: |
          mkdir target/
          cd target/
          gh --repo ${GITHUB_REPOSITORY} run download ${GITHUB_RUN_ID} -p "Inductor-*-XPU-E2E-*"
          find Inductor-*-XPU-E2E-*/ -maxdepth 1 -mindepth 1 -type d |sort -V |\
                  while read line; do rsync -az --delete $line/ $(basename $line)/; done
          rm -rf Inductor-*-XPU-E2E-* || true
      - name: Download Baseline Artifact
        run: |
          mkdir baseline/
          cd baseline/
          if [[ "${{ inputs.test_type }}" != *"ly" ]];then
            artifact_type="$(echo ${{ inputs.test_type }} |awk -F '-' '{print $1}')-nightly"
          else
            artifact_type="${{ inputs.test_type }}"
          fi
          gh --repo intel/torch-xpu-ops issue view ${REFERENCE_ISSUE_ID} --json body -q .body 2>&1 |tee body.txt
          REFERENCE_RUN_ID="$(cat body.txt |grep "Inductor-${artifact_type}-LTS2" |sed 's/.*: *//' || echo '')"
          if [ "${REFERENCE_RUN_ID}" != "" ];then
            gh --repo intel/torch-xpu-ops run download ${REFERENCE_RUN_ID} -p "Inductor-*-XPU-E2E-*"
            find Inductor-*-XPU-E2E-*/ -maxdepth 1 -mindepth 1 -type d |sort -V |\
                    while read line; do rsync -az --delete $line/ $(basename $line)/; done
            rm -rf Inductor-*-XPU-E2E-* || true
          fi
      - name: Upload Reference Run ID
        if: ${{ endsWith(inputs.test_type, 'ly') && steps.summary.outputs.e2e_result == 1 }}
        run: |
          gh --repo ${GITHUB_REPOSITORY} issue view ${REFERENCE_ISSUE_ID} --json body -q .body 2>&1 |tee new_body.txt 2>&1
          has_or_not="$(grep -c 'Inductor-${{ inputs.test_type }}-LTS2' new_body.txt || true)"
          if [ ${has_or_not} -ne 0 ];then
            sed -i "s/Inductor-${{ inputs.test_type }}-LTS2:.*/Inductor-${{ inputs.test_type }}-LTS2: ${GITHUB_RUN_ID}/" new_body.txt
          else
            echo "Inductor-${{ inputs.test_type }}-LTS2: ${GITHUB_RUN_ID}" |tee -a new_body.txt
          fi
          gh --repo ${GITHUB_REPOSITORY} issue edit ${REFERENCE_ISSUE_ID} --body-file new_body.txt

      - name: Result accuracy with release expected accuracy
        if: ${{ ! cancelled() }}
        run: |
          python .github/ci_expected_accuracy/check_expected.py --results-dir target/ \
              --expected .github/ci_expected_accuracy/expected_accuracy_lts.csv \
              --fail-on-regression
      - name: Result performance and accuracy regression check with baseline
        if: ${{ ! cancelled() }}
        run: |
          export PYTHONPATH=${{ github.workspace }}/.github/scripts
          python -m run_benchmarks.summary -t ./target -b ./baseline -o e2e_summary.xlsx
      - name: Upload Inductor E2E Summary
        if: ${{ ! cancelled() }}
        uses: actions/upload-artifact@v4
        with:
          name: Inductor-E2E-Summary
          path: e2e_summary.xlsx
