name: Linux E2E Test

on:
  workflow_call:

env:
  ddd: 4

jobs:
  test:
    runs-on: build
    container:
      image: ubuntu:24.04
      volumes:
        - ${{ github.workspace }}:${{ github.workspace }}
      env:
        fff: 6
    env:
      eee: 5
    steps:
      - name: Check runner
        shell: bash -xe {0}
        run: |
          printenv
      - name: Checkout torch-xpu-ops
        uses: actions/checkout@v4
      - name: Prepare test env
        uses: ./.github/actions/linux-testenv
