name: Performance Comparison

on:
  workflow_dispatch:
    inputs:
      target:
        required: true
        type: string
        default: ''
        description: Target run id
      baseline:
        required: true
        type: string
        default: ''
        description: Baseline run id

permissions: read-all

jobs:
  Performance-Comparison:
    env:
      GH_TOKEN: ${{ github.token }}
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -e -x -o pipefail {0}
    steps:
      - name: Cleanup workspace
        run: |
          rm -rf ./target ./baseline
      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' 
      - name: Checkout torch-xpu-ops
        uses: actions/checkout@v4
      - name: Downlaod artifacts
        run: |
          rm -rf target && mkdir target && cd target
          gh --repo ${GITHUB_REPOSITORY} run download ${{ inputs.target }} -p "Inductor-*-XPU-E2E-*"
          mv Inductor-*-XPU-E2E-*/* . && cd ..
          rm -rf baseline && mkdir baseline && cd baseline
          gh --repo ${GITHUB_REPOSITORY} run download ${{ inputs.baseline }} -p "Inductor-*-XPU-E2E-*"
          mv Inductor-*-XPU-E2E-*/* . && cd ..
      - name: Comparison result
        run: |
          python -m pip install pandas
          python .github/scripts/perf_comparison.py --xpu target --refer baseline >> ${GITHUB_STEP_SUMMARY}
