name: Build Triton wheels

on:
  workflow_call:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}-${{ github.event_name == 'workflow_dispatch' }}
  cancel-in-progress: true

jobs:
  build-wheel:
    name: "Build Triton Wheel"
    runs-on: pvc_rolling
    strategy:
      fail-fast: false
      matrix:
        py_vers: [ "3.10"]
        device: ["xpu"]
        docker-image: ["pytorch/manylinux2_28-builder:cpu"]
        include:
          - device: "xpu"
            rocm_version: ""
            runs_on: "pvc_rolling"
    timeout-minutes: 40
    env:
      DOCKER_IMAGE: intelgpu/ubuntu-22.04-lts2:2523.31
      PY_VERS: ${{ matrix.py_vers }}
      BUILD_DEVICE: ${{ matrix.device }}
      PLATFORM: 'manylinux_2_28_x86_64'
    steps:
      - name: Checkout public repo
        uses: actions/checkout@v4
        with:
          repository: 'pytorch/pytorch'
      - name: Checkout public repo
        uses: actions/checkout@v4
        with:
          path: torch-xpu-ops
      - name: Build Triton wheel
        env:
          IS_RELEASE_TAG: ${{ startsWith(github.event.ref, 'refs/tags/v') }}
        run: |
          set -x
          mkdir -p "${RUNNER_TEMP}/artifacts/"
          echo "release/3.6.x" > .ci/docker/ci_commit_pins/triton-xpu.txt
          echo "3.6.0" > .ci/docker/triton_xpu_version.txt
          cp torch-xpu-ops/.github/scripts/build_triton_wheel.py  .github/scripts/build_triton_wheel.py
          container_name=$(docker run \
            --tty \
            --detach \
            -v "${GITHUB_WORKSPACE}:/pytorch" \
            -v "${RUNNER_TEMP}/artifacts:/artifacts" \
            -w /artifacts/ \
            "${DOCKER_IMAGE}"      \
          )

          RELEASE=""
          WITH_CLANG_LDD=""
          if [[ "${IS_RELEASE_TAG}" == true ]]; then
            RELEASE="--release"
          fi

          PYTHON_EXECUTABLE="python3.10"

          docker exec -t "${container_name}" apt-get update && sudo apt-get install wget curl gcc g++ cmake git unzip zip libgl1 zlib1g-dev numactl -y libglib2.0-dev rsync jq python3.10 python3.10-dev python3.10-venv python3-pip
          docker exec -t "${container_name}" ln -sf /usr/bin/pip3 /usr/bin/pip
          docker exec -t "${container_name}" "${PYTHON_EXECUTABLE}"  -m pip install -U setuptools==78.1.0 pybind11==3.0.1 auditwheel wheel
          set +e
          docker exec -t "${container_name}" command -v pip
          has_pip=$?
          set -e
          if [ $has_pip -eq 0 ] ; then
              docker exec -t "${container_name}" pip install -U cmake --force-reinstall
          else
              docker exec -t "${container_name}" "${PYTHON_EXECUTABLE}"  -m pip install -U cmake --force-reinstall ninja
          fi

          if [[ ("${{ matrix.device }}" == "cuda" || "${{ matrix.device }}" == "rocm" || "${{ matrix.device }}" == "aarch64" ) ]]; then
            # With this install, it gets clang 16.0.6.
            docker exec -t "${container_name}" dnf install clang lld -y
            WITH_CLANG_LDD="--with-clang-ldd"
          fi

          docker exec -t "${container_name}" bash -c "${PYTHON_EXECUTABLE} /pytorch/.github/scripts/build_triton_wheel.py --device=$BUILD_DEVICE $RELEASE $WITH_CLANG_LDD"

          if [[ ("${{ matrix.device }}" == "cuda" || "${{ matrix.device }}" == "xpu") ]]; then
            docker exec -t "${container_name}"  bash -c "auditwheel repair --plat ${PLATFORM} //artifacts/*.whl"
          else
            docker exec -t "${container_name}"  bash -c "mkdir //artifacts/wheelhouse"
            docker exec -t "${container_name}"  bash -c "mv //artifacts/*.whl //artifacts/wheelhouse/"
          fi
          docker exec -t "${container_name}" chown -R 1000.1000 /artifacts/wheelhouse

      - uses: actions/upload-artifact@50769540e7f4bd5e21e526ee35c689e35e0d6874 # v4.4.0
        with:
          name: pytorch-triton-wheel-${{ matrix.py_vers }}-${{ matrix.device }}-${{ env.PLATFORM }}
          if-no-files-found: error
          path: ${{ runner.temp }}/artifacts/wheelhouse/*
