name: Hello World

on:
  push:
    branches:
      - clangtidy_actions

jobs:
  hello:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Hello World
        run: echo "Hello World"
