name: Hello World

on:
  pull_request:
    branches:
      - main

jobs:
  hello:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Hello World
        run: echo "Hello World"
