name: Nightly-OnDemand Tests Rolling

on:
  workflow_dispatch:
    inputs:
      node_name:
        type: string
        default: ''

permissions: read-all

jobs:
  get_runner:
    runs-on: linux.idc.xpu
    container:
      image: 'pytorch/manylinux2_28-builder:xpu-main'
      env:
        GH_TOKEN: ${{ github.token }}
        AGENT_TOOLSDIRECTORY: /tmp/_tools
    timeout-minutes: 300
    defaults:
      run:
        shell: bash -xe {0}
    steps:
      - name: Setup python
        uses: actions/setup-python@main
        with:
          python-version: pypy3.10
          check-latest: true
