name: Nightly-OnDemand Tests

on:
  workflow_dispatch:
    inputs:
      node_name:
        type: string
        default: ''
        description: 'PVC-7362,PVC-7363,PVC-7364,PVC-7365,PVC-7900,PVC-03004,PVC-03006'

permissions: read-all

env:
  aaa: 1

jobs:
  test:
    runs-on: build
    env:
      bbb: 2
    steps:
      - name: Checkout torch-xpu-ops
        uses: actions/checkout@v4
      - name: Prepare test env
        uses: ./.github/workflows/_linux_e2e.yml
