name: Nightly-OnDemand Tests Rolling

on:
  workflow_dispatch:
    inputs:
      node_name:
        type: string
        default: ''

permissions: read-all

jobs:
  get_runner:
    runs-on: ${{ inputs.node_name }}
    timeout-minutes: 480
    defaults:
      run:
        shell: bash -xe {0}
    steps:
      - name: test
        run: |
          sleep 36000
