name: Nightly-OnDemand Tests

on:
  workflow_dispatch:
    inputs:
      runner:
        type: string
        default: 'pvc_rolling'
        description: Runner to use

permissions: read-all

jobs:

  runner:
    runs-on: ${{ inputs.runner }}
    name: get-runner
    outputs:
      runner_id: ${{ steps.runner-info.outputs.runner_id }}
      user_id: ${{ steps.runner-info.outputs.user_id }}
      render_id: ${{ steps.runner-info.outputs.render_id }}
      hostname: ${{ steps.runner-info.outputs.hostname }}
      xpu_num: ${{ steps.runner-info.outputs.xpu_num }}
      cpus_per_xpu: ${{ steps.runner-info.outputs.cpus_per_xpu }}
    steps:
      - name: Cleanup workspace
        run: |
          sudo find ./ |grep -v "^\./$" |xargs sudo rm -rf
      - name: Checkout torch-xpu-ops
        uses: actions/checkout@v4
      - name: Get runner
        id: runner-info
        uses: ./.github/actions/get-runner

  debug:
    needs: runner
    runs-on: ${{ needs.runner.outputs.runner_id }}
    strategy:
      matrix:
        pytorch: [2.9.0.dev20250830+xpu, 2.9.0.dev20250906+xpu]
    container:
      image: mengfeili/intel-pvc-driver:1146-1136
      volumes:
        - ${{ github.workspace }}:${{ github.workspace }}
      options: --device=/dev/mem --device=/dev/dri --group-add video --security-opt seccomp=unconfined --cap-add=SYS_PTRACE --shm-size=8g
              -u ${{ needs.runner.outputs.user_id }}:${{ needs.runner.outputs.render_id }}
      env:
        xpu_num: ${{ needs.runner.outputs.xpu_num }}
        cpus_per_xpu: ${{ needs.runner.outputs.cpus_per_xpu }}
        AGENT_TOOLSDIRECTORY: /tmp/xpu-tool
    steps:
      - name: Checkout torch-xpu-ops
        uses: actions/checkout@v4
      - name: Prepare test env on ${{ needs.runner.outputs.hostname }}
        uses: ./.github/actions/linux-testenv
        with:
          pytorch: nightly_wheel
          pytorch_version: '==${{ matrix.pytorch }}'
          python: '3.10'
          suite: timm_models
      - name: Test
        run: |
          ./run.sh performance 0 cases.txt
      - name: Upload Inductor XPU UT Log
        if: ${{ ! cancelled() }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.pytorch }}
          path: ${{ github.workspace }}/logs
