name: Torch Nightly WHL Tests

on:
  workflow_dispatch:
    inputs:
      node_name:
        type: string
        default: ''

permissions: read-all

jobs:
  check-nodes-env:
    runs-on: ${{ inputs.node_name }}
    strategy:
      matrix:
        onednn: [v3.8.1, v3.9-rc]
    name: Benchdnn with ${{ matrix.onednn }}
    env:
      CC: icx
      CXX: icpx
    steps:
      - name: Cleanup
        run: |
          sudo rm -rf ./*
      - name: Build
        run: |
          source /opt/intel/oneapi/setvars.sh
          git clone https://github.com/uxlfoundation/oneDNN ${{ matrix.onednn }}
          cd ${{ matrix.onednn }}
          git checkout ${{ matrix.onednn }}
          git show -s
          mkdir build
          cd build
          cmake .. -DONEDNN_CPU_RUNTIME=SYCL -DONEDNN_GPU_RUNTIME=SYCL |tee ${{ github.workspace }}/logs/build.log
      - name: Test
        run: |
          source /opt/intel/oneapi/compiler/latest/env/vars.sh
          source /opt/intel/oneapi/pti/latest/env/vars.sh
          source /opt/intel/oneapi/umf/latest/env/vars.sh
          source /opt/intel/oneapi/ccl/latest/env/vars.sh
          source /opt/intel/oneapi/mpi/latest/env/vars.sh
          source /opt/intel/oneapi/tbb/latest/env/vars.sh
          cd ${{ matrix.onednn }}/build/test/benchdnn
          while read line
          do
            ./benchdnn -mode P $line |tee -a ${{ github.workspace }}/logs/test.log
          done < ~/mengfeil/benchdnn.txt
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.onednn }}
          path: ${{ github.workspace }}/logs
