name: pull

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - converted_to_draft
      - ready_for_review
      - labeled
    branches:
      - main
      - release/*

permissions: read-all

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:

  conditions-filter:
    if: ${{ github.repository_owner == 'intel' && github.event.pull_request.draft == false }}
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    env:
      GH_TOKEN: ${{ github.token }}
    outputs:
      src_changed: ${{ steps.check-files.outputs.src_changed }}
      has_label: ${{ steps.check-label.outputs.has_label }}
      disabled_tests: ${{ steps.check-pr-desc.outputs.disabled_tests }}
      pytorch: ${{ contains(steps.check-pr-desc.outputs.disabled_tests, 'disable_build') && 'nightly_wheel' || github.base_ref }}
    steps:
      - uses: dorny/paths-filter@v2
        id: check-files
        with:
          filters: |
            src_changed: 
              - 'cmake/**'
              - 'tools/**'
              - 'src/**.cmake'
              - 'CMakeLists.txt'
              - 'test/sycl/CMakeLists.txt'
              - 'src/xccl/CMakeLists.txt'
              - 'src/ATen/CMakeLists.txt'
              - 'src/CMakeLists.txt'
              - '.github/workflows/_windows_ut.yml'
      - name: Check Label
        id: check-label
        run: |
          echo "has_label=${{ contains(github.event.pull_request.labels.*.name, 'windows_ci') }}" >> $GITHUB_OUTPUT
      - name: Check PR infos
        id: check-pr-desc
        run: |
          set -x -e -o pipefail
          sudo apt update && sudo apt install -y dos2unix
          gh --repo ${GITHUB_REPOSITORY} pr view ${{ github.event.pull_request.number }} 2>&1 |tee pr-info.txt
          dos2unix pr-info.txt
          disabled_tests="$(awk '/disable_/{printf("%s ", $0)}' pr-info.txt)"
          echo "disabled_tests=${disabled_tests}" |tee "${GITHUB_OUTPUT}"

  linux-build:
    if: ${{ !contains(needs.conditions-filter.outputs.disabled_tests, 'disable_all') }}
    needs: [conditions-filter, preci-lint-check]
    secrets: inherit
    strategy:
      fail-fast: false
      matrix:
        build: [build]
    uses: ./.github/workflows/_linux_build.yml
    with:
      runner: pvc_rolling
      pytorch: ${{ needs.conditions-filter.outputs.pytorch }}

  clang-tidy-check:
    needs: [linux-build]
    if: ${{ github.repository_owner == 'intel' }}
    runs-on: pvc_rolling
    timeout-minutes: 60
    steps:
      - name: Run clang-tidy
        run: |
          cd torch-xpu-ops
          export ADDITIONAL_LINTRUNNER_ARGS="--take CLANGTIDY --all-files"
          bash .github/scripts/lintrunner.sh

