name: Scheduled Tests

on:
  schedule:
    # GMT+8 21:00 every workday (Build from source)
    - cron: '10 13 * * 0-4'
    # GMT+8 21:00 every workday (Nightly wheel)
    - cron: '30 13 * * 0-4'
    # GMT+8 00:00 Saturday (Build from source)
    - cron: '10 16 * * 5'
    # GMT+8 00:00 Saturday (Nightly wheel)
    - cron: '30 16 * * 5'

permissions: read-all

run-name: |
  ${{
    contains(github.event.schedule, '13') && 'Nightly' || 'Weekly'
  }} / ${{
    contains(github.event.schedule, '10') && 'build-from-source' || 'nightly-wheel'
  }}

jobs:
  scheduled-tests:
    if: ${{ github.repository_owner == 'intel' }}
    permissions: write-all
    uses: ./.github/workflows/_test_call.yml
    with:
      runner: 'pvc_rolling'
      is_scheduled_run: schedule
      ut: 'basic,op_ut,skipped_ut,xpu_profiling,xpu_distributed,microbench,windows'
      suite: 'huggingface,timm_models,torchbench,pt2e'
    secrets: inherit
